version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        working_dir: /var/www/html
